name: Atualizar Listas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # 🔥 ESSENCIAL para evitar erro 128

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar script
        run: python script.py

      - name: Commit e push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "update listas" || echo "sem mudanças"
          git push
